# Site settings
title: Jaume Barcelo
email: jaume dot barcelo dot cc
description: "CC-BY Creative Commons Attribution"
baseurl: ""
url: "http://jaume.barcelo.cc"
twitter_username: jaumebarcelo
github_username:  jbarcelo

# Build settings
markdown: kramdown
permalink: pretty
